"""Regenerate predicted_response with the Gemini API (responder-side twin of
scripts/gemini_judge_responses.py).

Takes an existing prediction.json — whose predicted_track_ids were produced by
the retrieval+rerank pipeline — rejoins each row to its conversation context +
the recommended tracks' metadata, and rewrites predicted_response via Gemini.
predicted_track_ids are left UNTOUCHED (this only swaps the LLM/response axis).
The output is a new prediction.json with the same rows, ready to validate +
submit (scripts/validate_prediction.py).

Why this exists: the challenge scores predicted_response with a Gemini judge on
Personalization + Explanation Quality (0.30 of the composite). The static
prediction.json carries no model provenance, so the response text may be
generated by any method. See project_responder_topn_ab_status_2026_06_04 memory
for the rules check (no rule bans external APIs; final code-upload required;
judge family is Gemini -> self-preference risk) and the top_n A/B (the local
v5-kto responder is best at top_n=1 because it was trained on a single grounded
track — that is responder-specific, NOT assumed to carry to Gemini).

Usage:
    GEMINI_API_KEY=...  python scripts/gemini_responder.py \
        --pred exp/inference/blindset_A/<tid>.json \
        --out  exp/inference/blindset_A/<tid>_gemini.json \
        --top-n 1
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
import time

import pandas as pd

MODEL = os.environ.get("GEMINI_RESPONDER_MODEL", "gemini-2.5-flash")
# best-of-N judge: cheaper/faster model scores candidates (generate with the
# strong responder model, judge with this one to keep cost down).
JUDGE_MODEL = os.environ.get("GEMINI_JUDGE_MODEL", "gemini-2.5-flash")
DEFAULT_TEMPS = (0.5, 0.8, 1.0)  # cycled across best-of-N candidates for diversity
DEFAULT_DATASET = "talkpl-ai/TalkPlayData-Challenge-Dataset"
ITEM_DB = "talkpl-ai/TalkPlayData-Challenge-Track-Metadata"

RESPONDER_INSTRUCTIONS = """You are an expert music recommender replying to a user mid-conversation.
Write ONE reply, 2-3 short sentences, no lists, no preamble.

Voice: be helpful, warm, and genuinely kind, but to the point — like a friend with great taste, not a
salesperson. Read the user's vibe — their mood, energy, and how they seem to be feeling right now — and
match it: if they're excited, share it; if they're winding down, stay easy and calm.

First, directly answer the user's MOST RECENT message — the reply must read as an on-point response to
what they just asked for, not a generic pitch.

From the candidate track(s) below, recommend the SINGLE best-fitting one and build the reply around it.
Mention a second track ONLY if it genuinely fits the same request; never pad the reply with extra tracks
just because they were provided, and never connect a track on a shallow coincidence (e.g. a word in the
title) — the link must be a real musical or taste fit.

Continuity: if earlier in this conversation the user liked a track, briefly connect your pick to it
through a real shared attribute (e.g. "like [earlier track]'s warm guitar, this one…"), and steer away
from qualities they rejected. Only do this when the connection is genuine — never invent a past
preference, and skip it entirely if there is no relevant history.

Cold start: if there is no prior history to build on, personalize from the user's current request and
stated goal — their mood, activity, and the qualities they just named — and ground the pick in the
track's real attributes. Do not fabricate past taste, and never fall back to a generic "here are some
songs you might like" line.

To score well you MUST do BOTH:
- PERSONALIZATION: tie the pick to something THIS user actually said AND to their current vibe (intent,
  mood, activity, taste). Reference it concretely; never be generic, and never present guesses about the
  user as facts.
- EXPLANATION: justify the pick with at least one real attribute of the recommended track (artist,
  title, genre, mood, instrumentation, era) drawn ONLY from what you were given, and link that attribute
  to the SPECIFIC thing the user asked for — not a generic "you'll like it".

Connect through the explanation, not by echoing: do NOT repeat the user's words back to them, and never
cut the concrete track detail to stay short — the specific reason the track fits their request is the
most important part of the reply.

Rules: lead with the recommendation; never open with a generic line; keep it tight — every sentence earns
its place; never invent or guess attributes you were not given; if unsure of something, leave it out so
nothing sounds made up. Return ONLY the reply text — no labels, headers, quotation marks, or description
of your reasoning."""


def _first(v):
    """HF metadata fields are often singleton lists; unwrap to a scalar."""
    if isinstance(v, list):
        return v[0] if v else None
    return v


def _track_inline(meta):
    """One-line 'Name by Artist — tag1, tag2' for a prior in-session rec, so the
    model can connect a new pick to what the user already liked via shared traits."""
    name = _first(meta.get("track_name"))
    artist = _first(meta.get("artist_name"))
    tags = meta.get("tags") or meta.get("tag_list") or []
    tags = tags if isinstance(tags, list) else [str(tags)]
    s = f"{name} by {artist}"
    if tags:
        s += f" — {', '.join(str(x) for x in tags[:4])}"
    return s


def _decade(release_date):
    """Map a release_date (HF field: a 'YYYY-MM-DD' string, a 'YYYY', or a
    singleton list of one) to a citable era label like '1990s'. Returns None for
    missing/malformed dates so a bogus era is never emitted into the prompt."""
    rd = _first(release_date)
    if rd is None:
        return None
    s = str(rd).strip()
    if len(s) < 4 or not s[:4].isdigit():
        return None
    return f"{(int(s[:4]) // 10) * 10}s"


def render_context(conversations, item_db_meta, target_turn):
    """Render the user-visible conversation up to (and including) the target
    user turn. Music turns are expanded to the recommended track's name AND its
    attributes (so the reply can build continuity from what the user liked); the
    target turn's own assistant/music reply is excluded (that is what we are
    generating)."""
    df = pd.DataFrame(conversations)
    lines = []
    hist = df[df["turn_number"] < target_turn]
    for _, t in hist.iterrows():
        role = t["role"]
        content = t["content"]
        if role == "music":
            role = "assistant"
            m = item_db_meta.get(str(content), {})
            inline = _track_inline(m)
            # Surface the recommender's prior-turn 'thought' (its reasoning for
            # that pick) so the reply can build on real continuity rather than
            # invent it. Prior turns only (hist is turn < target) -> leak-safe.
            # Guard against NaN (pandas fills missing 'thought' cells) and blanks.
            th = t.get("thought")
            if isinstance(th, str) and th.strip():
                content = f"[recommended: {inline} | why: {th.strip()}]"
            else:
                content = f"[recommended: {inline}]"
        lines.append(f"{role}: {content}")
    cur = df[(df["turn_number"] == target_turn) & (df["role"] == "user")]
    if len(cur):
        lines.append(f"user: {cur.iloc[0]['content']}")
    return "\n".join(lines)


def format_tracks(tids, item_db_meta, n=1):
    """Format the top-n recommended tracks as grounding for the reply.
    Skips ids with no metadata (never emits a bare 'None by None')."""
    out = []
    for tid in (tids or [])[:n]:
        m = item_db_meta.get(str(tid))
        if not m:
            continue
        name = _first(m.get("track_name"))
        artist = _first(m.get("artist_name"))
        if name is None and artist is None:
            continue
        tags = m.get("tags") or m.get("tag_list") or []
        tags = tags if isinstance(tags, list) else [str(tags)]
        part = f"{name} by {artist}"
        album = _first(m.get("album_name"))
        if album:
            part += f" (album {album})"
        if tags:
            part += f" [{', '.join(str(x) for x in tags[:5])}]"
        # Era: a concrete, citable attribute the rubric rewards. The prompt only
        # lets the model mention attributes present in this block, so without it
        # the era is simply unavailable. Omitted entirely when unknown.
        era = _decade(m.get("release_date"))
        if era:
            part += f" — era {era}"
        out.append(part)
    return "; ".join(out) if out else "(none)"


def render_user_context(user_profile):
    """Compact 'User context' line from STATED preferences only
    (preferred_musical_culture, preferred_language). Inferred demographics
    (age/gender/country) are deliberately excluded: the judge scores
    personalization on what the user actually signalled, and presenting
    demographic guesses risks reading as stereotyping (could LOWER the score).
    Returns '' when no stated preference is present."""
    if not user_profile:
        return ""
    parts = []
    culture = (user_profile.get("preferred_musical_culture") or "").strip()
    lang = (user_profile.get("preferred_language") or "").strip()
    if culture:
        parts.append(f"Preferred musical culture: {culture}")
    if lang:
        parts.append(f"Preferred language: {lang}")
    return " | ".join(parts)


def goal_progress_tally(assessments, target_turn):
    """One-line tally of PRIOR picks' goal progress from
    goal_progress_assessments, so the reply can read the trajectory and keep
    momentum. Only turns strictly before target_turn count — the target turn's
    assessment is the label for the gold we're generating and MUST be excluded.
    Returns '' when there is no prior signal."""
    if not assessments:
        return ""
    moved = missed = 0
    for a in assessments:
        try:
            tn = int(a.get("turn_number"))
        except (TypeError, ValueError):
            continue
        if tn >= target_turn:
            continue
        v = a.get("goal_progress_assessment")
        if v == "MOVES_TOWARD_GOAL":
            moved += 1
        elif v == "DOES_NOT_MOVE_TOWARD_GOAL":
            missed += 1
    if moved == 0 and missed == 0:
        return ""
    return f"Goal progress so far: {moved} moved toward, {missed} missed"


# Few-shot style references. REAL tracks + REAL user requests curated from the
# TalkPlayData train set's high-GPA turns (the dataset gold is noisy/often
# misaligned, so these were hand-verified for alignment and trimmed of generic
# filler openers). Each models the target pattern: answer the latest message,
# lead with ONE best-fit track, tie it to what the user said, cite a concrete
# attribute, natural tone. Labeled "do not reuse" so the model copies STYLE,
# not these example tracks.
FEW_SHOT_EXAMPLES = """=== EXAMPLES (style reference only — do not reuse these tracks) ===
[user]: I love 'With A Little Help From My Friends' — that collaborative, Sgt. Pepper's-era feel. Could you suggest another Beatles track from around 1967, something that showcases their more psychedelic, artistic side?
[tracks]: Strawberry Fields Forever - Remastered by The Beatles
[reply]: For that 1967 psychedelic side, go straight to "Strawberry Fields Forever" — it's the Beatles at their most experimental and dreamlike, all layered, surreal textures, but still rooted in the melodic pop-rock you love from that era.

[user]: This is exactly what I wanted — a beautiful, piano-focused jazz track. Got any more like it?
[tracks]: Lucky To Be Me by Bill Evans
[reply]: Then you'll love "Lucky To Be Me" by Bill Evans — it's classic piano-led jazz, sparse and introspective, the kind of delicate, melodic playing that rewards close listening.

[user]: "Dog Days Are Over" is exactly the vivid, dramatic storytelling I was hoping for — that emotional intensity is perfect. More like this?
[tracks]: Cosmic Love by Florence + The Machine
[reply]: Stay with Florence + The Machine and try "Cosmic Love" — just as epic and dramatic, built on Florence's soaring vocals and a surging, cathartic swell that matches the emotional intensity you're after."""


def build_prompt(context, tracks_str, listener_goal, user_context="", goal_progress=""):
    """Assemble the responder prompt from the rubric instructions, few-shot style
    examples, the conversation, optional stated user context + goal-progress
    momentum, the recommended tracks, and (optionally) the goal."""
    parts = [RESPONDER_INSTRUCTIONS, "", FEW_SHOT_EXAMPLES,
             "", "=== CONVERSATION ===", context]
    if user_context:
        parts += ["", "=== USER CONTEXT (stated preferences) ===", user_context]
    if listener_goal:
        parts += ["", f"Listener goal: {listener_goal}"]
    if goal_progress:
        parts += ["", goal_progress]
    parts += ["", "=== RECOMMENDED TRACK(S) TO PRESENT ===", tracks_str,
              "", "Reply:"]
    return "\n".join(parts)


STRUCTURED_INSTRUCTIONS = """You are an expert music recommender. FIRST analyze the user, THEN reply.

Return ONLY a JSON object with exactly these keys:
{
  "user_state": {"mood": "...", "intent": "...", "energy": "...", "sonic_pref": "...",
                 "era_pref": "...", "familiarity": "..."},
  "fit": "...",
  "reply": "..."
}

- user_state: infer each axis from the conversation; use "unknown" for any axis the user did not signal.
  This is PRIVATE reasoning to guide the reply — it is never shown to the user.
- fit: for each axis that matters, name the concrete attribute of the recommended track(s) that satisfies it.
- reply: the final message to send the user. It MUST:
    * directly answer the user's MOST RECENT message and what they actually asked for — the reply has to
      read as an on-point response to that request, not a description of your analysis;
    * ground personalization ONLY in preferences the user explicitly stated in the conversation; do NOT
      present inferred guesses about their mood/taste as if they were facts the user told you;
    * cite ONLY attributes that appear in the RECOMMENDED TRACK(S) block; if an attribute is not listed
      there, do not mention it and do not invent it;
    * be 2-3 natural sentences, no lists, no preamble, and must NOT mention these JSON keys or your analysis;
    * never be generic and never over-claim — if you are unsure of something, leave it out rather than
      guess, so nothing in the reply sounds made up.

Output ONLY the JSON object."""


def build_structured_prompt(context, tracks_str, listener_goal, user_context="", goal_progress=""):
    """CoT-style prompt: the model fills personalization axes + a per-axis track
    'fit' (hidden scaffolding) before writing the final `reply`. Only `reply` is
    submitted (see parse_structured_reply)."""
    parts = [STRUCTURED_INSTRUCTIONS, "", "=== CONVERSATION ===", context]
    if user_context:
        parts += ["", "=== USER CONTEXT (stated preferences) ===", user_context]
    if listener_goal:
        parts += ["", f"Listener goal: {listener_goal}"]
    if goal_progress:
        parts += ["", goal_progress]
    parts += ["", "=== RECOMMENDED TRACK(S) TO PRESENT ===", tracks_str, "", "JSON:"]
    return "\n".join(parts)


def parse_structured_reply(text):
    """Extract the `reply` string from the model's JSON output. Returns None if
    it can't be parsed or `reply` is missing/empty — the caller then falls back
    (we never submit raw JSON as the response)."""
    if not text:
        return None
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        return None
    blob = m.group(0)
    try:
        d = json.loads(blob)
        reply = d.get("reply") if isinstance(d, dict) else None
        if isinstance(reply, str) and reply.strip():
            return reply.strip()
        return None
    except Exception:
        # Tolerate trailing junk / minor malformation: grab the reply value directly.
        # Use the LAST match so a nested decoy `reply` (e.g. inside user_state)
        # doesn't win over the real top-level one.
        rms = re.findall(r'"reply"\s*:\s*"((?:[^"\\]|\\.)*)"', blob, re.DOTALL)
        if not rms:
            return None
        captured = rms[-1]
        try:
            val = json.loads('"' + captured + '"')
        except Exception:
            val = captured
        val = val.strip()
        return val or None


def build_output_row(pred_row, new_response):
    """Submission row: preserve identity + predicted_track_ids, replace
    predicted_response. Drops any extra fields so the output matches the
    validator's expected schema exactly."""
    return {
        "session_id": pred_row["session_id"],
        "user_id": pred_row["user_id"],
        "turn_number": pred_row["turn_number"],
        "predicted_track_ids": pred_row["predicted_track_ids"],
        "predicted_response": new_response,
    }


def _is_rate_limited(err_str):
    es = err_str.lower()
    return ("429" in err_str or "resourceexhausted" in es
            or "quota" in es or "exhausted" in es)


def _call_model(model, prompt, sleep_fn=time.sleep, max_attempts=6, gen_config=None):
    """Raw Gemini call with retry/backoff on rate limits. Returns the raw text,
    or None if every attempt fails (rate-limit exhausted, API error, or a
    blocked/empty candidate whose `.text` accessor raises)."""
    for attempt in range(max_attempts):
        try:
            kw = {"generation_config": gen_config} if gen_config else {}
            resp = model.generate_content(prompt, **kw)
            return resp.text or ""
        except Exception as e:  # noqa: BLE001 — API raises a variety of types
            es = str(e)
            if _is_rate_limited(es) and attempt < max_attempts - 1:
                m = re.search(r"retry in ([\d.]+)s", es)
                wait = (float(m.group(1)) + 1.0) if m else min(60.0, 5.0 * (attempt + 1))
                print(f"  rate-limited, waiting {wait:.0f}s (attempt {attempt+1}/{max_attempts})")
                sleep_fn(wait)
            else:
                print(f"  API error: {e!r}")
                return None
    return None


def generate_response(model, prompt, fallback, max_attempts=6,
                      sleep_fn=time.sleep, parse_fn=None):
    """Single-shot reply. Returns the stripped reply text, or `fallback` (the
    row's original response) if the call fails or yields empty/unparseable text
    — we never drop a row's response.

    `parse_fn` (used by --structured-personality) post-processes the raw text;
    if it returns a falsy value we fall back rather than submit raw text."""
    raw = _call_model(model, prompt, sleep_fn=sleep_fn, max_attempts=max_attempts)
    if raw is None:
        return fallback
    text = parse_fn(raw) if parse_fn else raw.strip()
    return text if text else fallback


JUDGE_INSTRUCTIONS = """You score a music recommender's reply to a user on TWO INDEPENDENT axes, 1-5 each.
Judge ONLY the written reply (text quality) — not whether the recommended track is the "right" pick.

PERSONALIZATION — does the reply reflect THIS user's stated intent, mood, and taste?
  5 = clearly tailored: references something the user ACTUALLY said and ties the pick to their current vibe.
  3 = partly tailored but also generic, or leans on taste the user never stated.
  1 = generic; could be sent to anyone; ignores what the user asked for.
  Example 5: "Since you wanted something dramatic to wind down to, ..."   Example 1: "Here are some songs you might like."

EXPLANATION_QUALITY — does it give a concrete, accurate reason citing real attributes of the recommended track?
  5 = names a specific attribute (artist, genre, mood, instrumentation, era) and links it to what the user asked.
  3 = gives a reason, but vague or only loosely tied to the request.
  1 = no real reason, or vague / over-claimed / hallucinated attributes.
  Example 5: "...its sparse piano and aching vocal match the melancholy you're after."   Example 1: "It's a great track, enjoy!"

Score the two axes INDEPENDENTLY. Return ONLY a JSON object: {"personalization": <1-5>, "explanation_quality": <1-5>}"""


def build_judge_prompt(context, tracks_str, reply):
    """Prompt the judge model to score one candidate reply on the two axes."""
    return (f"{JUDGE_INSTRUCTIONS}\n\n=== CONVERSATION ===\n{context}\n\n"
            f"=== RECOMMENDED TRACKS ===\n{tracks_str}\n\n"
            f"=== REPLY TO SCORE ===\n{reply}\n\nReturn only the JSON.")


def parse_judge_score(text):
    """Sum of personalization + explanation_quality from the judge JSON; None if
    unparseable or an axis is missing (so unscored candidates rank last)."""
    if not text:
        return None
    m = re.search(r"\{[^{}]*\}", text, re.DOTALL)
    if not m:
        return None
    try:
        d = json.loads(m.group(0))
        return float(d["personalization"]) + float(d["explanation_quality"])
    except Exception:
        return None


def pick_best(scored):
    """`scored`: list of (reply, score|None). Return the reply with the highest
    score; if no candidate was scored, return the first reply; [] -> None."""
    if not scored:
        return None
    real = [(r, s) for r, s in scored if s is not None]
    if real:
        return max(real, key=lambda rs: rs[1])[0]
    return scored[0][0]


PAIRWISE_INSTRUCTIONS = """Compare two music-recommender replies to the SAME user and pick the better one on TWO axes:
PERSONALIZATION: reflects THIS user's stated intent, mood, and taste (not generic).
EXPLANATION_QUALITY: gives a concrete, accurate reason citing real attributes of the recommended track.
Pick the single better reply overall. Answer with ONLY the letter A or B."""


def build_pairwise_prompt(context, tracks_str, reply_a, reply_b):
    """Prompt the judge to pick the better of two candidate replies (A vs B)."""
    return (f"{PAIRWISE_INSTRUCTIONS}\n\n=== CONVERSATION ===\n{context}\n\n"
            f"=== RECOMMENDED TRACKS ===\n{tracks_str}\n\n"
            f"=== REPLY A ===\n{reply_a}\n\n=== REPLY B ===\n{reply_b}\n\n"
            "Which reply is better? Answer ONLY 'A' or 'B'.")


def parse_pairwise_verdict(text):
    """Extract 'A' or 'B' from the judge output; None if neither is clearly given."""
    if not text:
        return None
    m = re.search(r"\b([AB])\b", text.strip().upper())
    return m.group(1) if m else None


def _a_beats_b(judge_model, context, tracks_str, a, b, sleep_fn=time.sleep, swap=None):
    """True if reply `a` is judged better than `b`. Order is randomized per call
    (swap=None) to cancel the judge's A/B position bias; pass swap=False/True for
    deterministic tests. Judge runs at temperature 0 for stable picks. An
    unparseable/tie verdict keeps the incumbent (`a`)."""
    if swap is None:
        swap = random.random() < 0.5
    left, right = (b, a) if swap else (a, b)
    raw = _call_model(judge_model, build_pairwise_prompt(context, tracks_str, left, right),
                      sleep_fn=sleep_fn, gen_config={"temperature": 0.0})
    v = parse_pairwise_verdict(raw)
    if v is None:
        return True  # tie -> incumbent keeps its place
    left_wins = (v == "A")
    a_is_left = not swap
    return left_wins == a_is_left


def select_pairwise_koth(judge_model, context, tracks_str, cands, sleep_fn=time.sleep):
    """King-of-the-hill: carry a champion through the list, N-1 pairwise compares."""
    champ = cands[0]
    for c in cands[1:]:
        if not _a_beats_b(judge_model, context, tracks_str, champ, c, sleep_fn=sleep_fn):
            champ = c
    return champ


def select_round_robin(judge_model, context, tracks_str, cands, sleep_fn=time.sleep):
    """Every candidate vs every other (C(n,2) compares); return the most-wins reply.
    Robust to noisy/non-transitive comparisons at higher cost."""
    wins = [0] * len(cands)
    for i in range(len(cands)):
        for j in range(i + 1, len(cands)):
            if _a_beats_b(judge_model, context, tracks_str, cands[i], cands[j], sleep_fn=sleep_fn):
                wins[i] += 1
            else:
                wins[j] += 1
    return cands[max(range(len(cands)), key=lambda k: wins[k])]


def generate_best_of_n(gen_model, judge_model, prompt, judge_context, tracks_str,
                       fallback, n, temperatures, sleep_fn=time.sleep, parse_fn=None,
                       select="pointwise"):
    """Generate n candidate replies (varied temperature), then SELECT the best:
      - 'pointwise'   : score each reply 0-5 x2 independently, take the argmax (N judge calls)
      - 'pairwise'    : king-of-the-hill A-vs-B comparisons (N-1 judge calls, sharper)
      - 'round_robin' : all pairs, most wins (C(N,2) judge calls, noise-robust)
    Falls back to the row's original response if no candidate is produced."""
    cands = []
    for i in range(max(1, n)):
        t = temperatures[i % len(temperatures)]
        raw = _call_model(gen_model, prompt, sleep_fn=sleep_fn,
                          gen_config={"temperature": t})
        if raw is None:
            continue
        reply = parse_fn(raw) if parse_fn else raw.strip()
        if reply:
            cands.append(reply)
    if not cands:
        return fallback
    if len(cands) == 1:
        return cands[0]
    if select == "pairwise":
        return select_pairwise_koth(judge_model, judge_context, tracks_str, cands, sleep_fn=sleep_fn)
    if select == "round_robin":
        return select_round_robin(judge_model, judge_context, tracks_str, cands, sleep_fn=sleep_fn)
    scored = []
    for r in cands:
        jraw = _call_model(judge_model, build_judge_prompt(judge_context, tracks_str, r),
                          sleep_fn=sleep_fn, gen_config={"temperature": 0.0})
        scored.append((r, parse_judge_score(jraw)))
    return pick_best(scored)


def _load_item_meta():
    import datasets as _d
    from datasets import load_dataset
    idb = load_dataset(ITEM_DB)
    idb = _d.concatenate_datasets([idb[s] for s in idb])
    meta = {}
    for r in idb:
        meta[str(r["track_id"])] = {
            "track_name": r.get("track_name"),
            "artist_name": r.get("artist_name"),
            "album_name": r.get("album_name"),
            "tags": r.get("tag_list"),
            # release_date -> era (citable). popularity carried for a future,
            # separately-measured variant (kept out of the prompt text for now
            # to avoid judge-penalized over-claims).
            "release_date": r.get("release_date"),
            "popularity": r.get("popularity"),
        }
    return meta


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pred", required=True, help="existing prediction.json (keeps predicted_track_ids)")
    ap.add_argument("--out", required=True, help="output prediction.json with regenerated responses")
    ap.add_argument("--dataset", default=DEFAULT_DATASET, help="HF dataset for conversation context (split=test)")
    ap.add_argument("--top-n", type=int, default=1, help="how many reranked tracks the responder sees")
    ap.add_argument("--limit", type=int, default=0, help="cap rows (0 = all)")
    ap.add_argument("--sleep", type=float, default=0.2, help="seconds between API calls")
    ap.add_argument("--structured-personality", action="store_true",
                    help="structured_personality (CoT) mode: the model fills personalization axes "
                         "(mood/intent/energy/sonic_pref/era_pref/familiarity) + a per-axis track "
                         "'fit' before writing; only the JSON `reply` is submitted")
    ap.add_argument("--best-of", type=int, default=1,
                    help="best-of-N: generate N replies (varied temperature), score each with the "
                         "judge model, submit the highest-scoring (1 = single shot, default)")
    ap.add_argument("--judge-model", default=JUDGE_MODEL,
                    help="model that scores best-of-N candidates (default: cheap flash)")
    ap.add_argument("--select", default="pointwise",
                    choices=["pointwise", "pairwise", "round_robin"],
                    help="best-of-N selection: pointwise (0-5 score each, N calls), "
                         "pairwise (king-of-the-hill A-vs-B, N-1 calls), "
                         "round_robin (all pairs, C(N,2) calls). Default pointwise.")
    args = ap.parse_args()

    if args.top_n < 1:
        sys.exit("ERROR: --top-n must be >= 1 (the responder needs at least one track to explain).")
    if args.best_of < 1:
        sys.exit("ERROR: --best-of must be >= 1.")
    key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not key:
        sys.exit("ERROR: set GEMINI_API_KEY (Colab secret) before running.")
    import google.generativeai as genai
    from datasets import load_dataset
    genai.configure(api_key=key)
    model = genai.GenerativeModel(MODEL)
    judge_model = genai.GenerativeModel(args.judge_model) if args.best_of > 1 else None

    preds = json.load(open(args.pred))
    if args.limit:
        preds = preds[: args.limit]
    mode = "structured_personality" if args.structured_personality else "plain"
    bo = f", best_of={args.best_of} (judge={args.judge_model})" if args.best_of > 1 else ""
    print(f"[responder] {len(preds)} rows from {args.pred} via {MODEL} "
          f"(top_n={args.top_n}, mode={mode}{bo})")

    ds = load_dataset(args.dataset, split="test")
    sess_by_id = {s["session_id"]: s for s in ds}
    item_db_meta = _load_item_meta()

    out_rows, n_gen, n_fallback = [], 0, 0
    for i, p in enumerate(preds):
        # Per-row guard: a single malformed session (unexpected schema, missing
        # conversations, bad goal shape) falls back to the original response
        # instead of aborting the whole run. Row count is always conserved.
        fallback = p.get("predicted_response", "") or ""
        try:
            sess = sess_by_id.get(p["session_id"])
            if sess is None:
                new_resp = fallback
            else:
                ctx = render_context(sess["conversations"], item_db_meta, p["turn_number"])
                tracks = format_tracks(p.get("predicted_track_ids"), item_db_meta, n=args.top_n)
                goal = ((sess.get("conversation_goal") or {}).get("listener_goal") or "").strip()
                user_ctx = render_user_context(sess.get("user_profile"))
                gprog = goal_progress_tally(sess.get("goal_progress_assessments"),
                                            p["turn_number"])
                if args.structured_personality:
                    prompt = build_structured_prompt(ctx, tracks, goal,
                                                     user_context=user_ctx,
                                                     goal_progress=gprog)
                    parse_fn = parse_structured_reply
                else:
                    prompt = build_prompt(ctx, tracks, goal,
                                          user_context=user_ctx, goal_progress=gprog)
                    parse_fn = None
                if args.best_of > 1:
                    new_resp = generate_best_of_n(model, judge_model, prompt, ctx, tracks,
                                                  fallback, n=args.best_of,
                                                  temperatures=list(DEFAULT_TEMPS),
                                                  parse_fn=parse_fn, select=args.select)
                else:
                    new_resp = generate_response(model, prompt, fallback, parse_fn=parse_fn)
        except Exception as e:  # noqa: BLE001 — never let one row kill the run
            print(f"  row {i} ({p.get('session_id')}): error, keeping original response: {e!r}")
            new_resp = fallback
        if new_resp == fallback:
            n_fallback += 1
        else:
            n_gen += 1
        out_rows.append(build_output_row(p, new_resp))
        if args.sleep:
            time.sleep(args.sleep)
        if (i + 1) % 25 == 0:
            print(f"  {i+1}/{len(preds)} (generated={n_gen}, fallback={n_fallback})")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    json.dump(out_rows, open(args.out, "w"), ensure_ascii=False)
    print(f"\n[responder] wrote {len(out_rows)} rows -> {args.out} "
          f"(generated={n_gen}, fallback={n_fallback})")
    # Loud guard: if NOTHING was generated, every row silently kept its original
    # response — most likely the API/SDK rejected the request (e.g. the best-of-N
    # generation_config). Surface it so an all-fallback no-op isn't mistaken for a
    # successful run.
    if n_gen == 0:
        print("\n*** WARNING: 0 rows generated — ALL fell back to the original "
              "response. This output is a no-op (not the Gemini responder). "
              "Check the API key / model / "
              + ("generation_config (best-of-N) " if args.best_of > 1 else "")
              + "before submitting. ***")


if __name__ == "__main__":
    main()
