"""Regenerate predicted_response with the Gemini API (responder-side twin of
scripts/gemini_judge_responses.py).

Takes an existing prediction.json — whose predicted_track_ids were produced by
the retrieval+rerank pipeline — rejoins each row to its conversation context +
the recommended tracks' metadata, and rewrites predicted_response via Gemini.
predicted_track_ids are left UNTOUCHED (this only swaps the LLM/response axis).
The output is a new prediction.json with the same rows, ready to validate +
submit (scripts/validate_prediction.py).

Why this exists: the challenge scores predicted_response with a Gemini judge on
Personalization + Explanation Quality (0.30 of the composite). The static
prediction.json carries no model provenance, so the response text may be
generated by any method. See project_responder_topn_ab_status_2026_06_04 memory
for the rules check (no rule bans external APIs; final code-upload required;
judge family is Gemini -> self-preference risk) and the top_n A/B (the local
v5-kto responder is best at top_n=1 because it was trained on a single grounded
track — that is responder-specific, NOT assumed to carry to Gemini).

Usage:
    GEMINI_API_KEY=...  python scripts/gemini_responder.py \
        --pred exp/inference/blindset_A/<tid>.json \
        --out  exp/inference/blindset_A/<tid>_gemini.json \
        --top-n 1
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time

import pandas as pd

MODEL = os.environ.get("GEMINI_RESPONDER_MODEL", "gemini-2.5-flash")
DEFAULT_DATASET = "talkpl-ai/TalkPlayData-Challenge-Dataset"
ITEM_DB = "talkpl-ai/TalkPlayData-Challenge-Track-Metadata"

RESPONDER_INSTRUCTIONS = """You are an expert music recommender replying to a user mid-conversation.
Write ONE warm, natural reply (2-3 sentences, no lists, no preamble).

First, directly answer the user's MOST RECENT message — the reply must read as an on-point response to
what they just asked for, not a generic pitch.

From the candidate track(s) below, recommend the SINGLE best-fitting one and build the reply around it.
Mention a second track ONLY if it genuinely fits the same request; never pad the reply with extra tracks
just because they were provided, and never connect a track on a shallow coincidence (e.g. a word in the
title) — the link must be a real musical or taste fit.

To score well you MUST do BOTH:
- PERSONALIZATION: tie the pick to something THIS user actually said (intent, mood, activity, taste).
  Reference it concretely; do not be generic, and do not present guesses about the user as facts.
- EXPLANATION: justify the pick with at least one real attribute of the recommended track (artist,
  title, genre, mood, instrumentation, era) drawn ONLY from what you were given, and say WHY it fits.

Rules: lead with the recommendation; sound like a knowledgeable friend, not a sales pitch; never open
with a generic line; never invent or guess attributes you were not given; if unsure of something, leave
it out so nothing sounds made up. Return ONLY the reply text — no labels, headers, quotation marks, or
description of your reasoning."""


def _first(v):
    """HF metadata fields are often singleton lists; unwrap to a scalar."""
    if isinstance(v, list):
        return v[0] if v else None
    return v


def render_context(conversations, item_db_meta, target_turn):
    """Render the user-visible conversation up to (and including) the target
    user turn. Music turns are expanded to the recommended track's name; the
    target turn's own assistant/music reply is excluded (that is what we are
    generating)."""
    df = pd.DataFrame(conversations)
    lines = []
    hist = df[df["turn_number"] < target_turn]
    for _, t in hist.iterrows():
        role = t["role"]
        content = t["content"]
        if role == "music":
            role = "assistant"
            m = item_db_meta.get(str(content), {})
            content = f"[recommended: {_first(m.get('track_name'))} by {_first(m.get('artist_name'))}]"
        lines.append(f"{role}: {content}")
    cur = df[(df["turn_number"] == target_turn) & (df["role"] == "user")]
    if len(cur):
        lines.append(f"user: {cur.iloc[0]['content']}")
    return "\n".join(lines)


def format_tracks(tids, item_db_meta, n=1):
    """Format the top-n recommended tracks as grounding for the reply.
    Skips ids with no metadata (never emits a bare 'None by None')."""
    out = []
    for tid in (tids or [])[:n]:
        m = item_db_meta.get(str(tid))
        if not m:
            continue
        name = _first(m.get("track_name"))
        artist = _first(m.get("artist_name"))
        if name is None and artist is None:
            continue
        tags = m.get("tags") or m.get("tag_list") or []
        tags = tags if isinstance(tags, list) else [str(tags)]
        part = f"{name} by {artist}"
        album = _first(m.get("album_name"))
        if album:
            part += f" (album {album})"
        if tags:
            part += f" [{', '.join(str(x) for x in tags[:5])}]"
        out.append(part)
    return "; ".join(out) if out else "(none)"


# Few-shot style references. Diverse scenarios (refinement, discovery) that each
# model the target pattern: answer the latest message, lead with ONE best-fit
# track, tie it to what the user said, cite a concrete attribute, natural tone.
# Labeled "do not reuse" so the model copies the STYLE, not these example tracks.
FEW_SHOT_EXAMPLES = """=== EXAMPLES (style reference only — do not reuse these tracks) ===
[user]: just finished a long run, want to cool down
[recommended]: Weightless by Marconi Union
[user]: nice but too ambient — something with a gentle beat and vocals
[tracks]: Saturn by Sleeping at Last [ambient pop, strings, calm, vocals]
[reply]: Then let's keep it calm but add a pulse — Saturn by Sleeping at Last is ambient pop, so you still get that mellow, string-laden wind-down but with real vocals and a gentle beat instead of pure atmosphere.

[user]: I love early Daft Punk, anything similar but newer?
[tracks]: Midnight City by M83 [synthpop, anthemic, 2010s, electronic]
[reply]: If it's that euphoric, synth-driven build you love in early Daft Punk, try Midnight City by M83 — same anthemic electronic rush, just from the 2010s. Different act, same goosebumps."""


def build_prompt(context, tracks_str, listener_goal):
    """Assemble the responder prompt from the rubric instructions, few-shot style
    examples, the conversation, the recommended tracks, and (optionally) the goal."""
    parts = [RESPONDER_INSTRUCTIONS, "", FEW_SHOT_EXAMPLES,
             "", "=== CONVERSATION ===", context]
    if listener_goal:
        parts += ["", f"Listener goal: {listener_goal}"]
    parts += ["", "=== RECOMMENDED TRACK(S) TO PRESENT ===", tracks_str,
              "", "Reply:"]
    return "\n".join(parts)


STRUCTURED_INSTRUCTIONS = """You are an expert music recommender. FIRST analyze the user, THEN reply.

Return ONLY a JSON object with exactly these keys:
{
  "user_state": {"mood": "...", "intent": "...", "energy": "...", "sonic_pref": "...",
                 "era_pref": "...", "familiarity": "..."},
  "fit": "...",
  "reply": "..."
}

- user_state: infer each axis from the conversation; use "unknown" for any axis the user did not signal.
  This is PRIVATE reasoning to guide the reply — it is never shown to the user.
- fit: for each axis that matters, name the concrete attribute of the recommended track(s) that satisfies it.
- reply: the final message to send the user. It MUST:
    * directly answer the user's MOST RECENT message and what they actually asked for — the reply has to
      read as an on-point response to that request, not a description of your analysis;
    * ground personalization ONLY in preferences the user explicitly stated in the conversation; do NOT
      present inferred guesses about their mood/taste as if they were facts the user told you;
    * cite ONLY attributes that appear in the RECOMMENDED TRACK(S) block; if an attribute is not listed
      there, do not mention it and do not invent it;
    * be 2-3 natural sentences, no lists, no preamble, and must NOT mention these JSON keys or your analysis;
    * never be generic and never over-claim — if you are unsure of something, leave it out rather than
      guess, so nothing in the reply sounds made up.

Output ONLY the JSON object."""


def build_structured_prompt(context, tracks_str, listener_goal):
    """CoT-style prompt: the model fills personalization axes + a per-axis track
    'fit' (hidden scaffolding) before writing the final `reply`. Only `reply` is
    submitted (see parse_structured_reply)."""
    parts = [STRUCTURED_INSTRUCTIONS, "", "=== CONVERSATION ===", context]
    if listener_goal:
        parts += ["", f"Listener goal: {listener_goal}"]
    parts += ["", "=== RECOMMENDED TRACK(S) TO PRESENT ===", tracks_str, "", "JSON:"]
    return "\n".join(parts)


def parse_structured_reply(text):
    """Extract the `reply` string from the model's JSON output. Returns None if
    it can't be parsed or `reply` is missing/empty — the caller then falls back
    (we never submit raw JSON as the response)."""
    if not text:
        return None
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        return None
    blob = m.group(0)
    try:
        d = json.loads(blob)
        reply = d.get("reply") if isinstance(d, dict) else None
        if isinstance(reply, str) and reply.strip():
            return reply.strip()
        return None
    except Exception:
        # Tolerate trailing junk / minor malformation: grab the reply value directly.
        # Use the LAST match so a nested decoy `reply` (e.g. inside user_state)
        # doesn't win over the real top-level one.
        rms = re.findall(r'"reply"\s*:\s*"((?:[^"\\]|\\.)*)"', blob, re.DOTALL)
        if not rms:
            return None
        captured = rms[-1]
        try:
            val = json.loads('"' + captured + '"')
        except Exception:
            val = captured
        val = val.strip()
        return val or None


def build_output_row(pred_row, new_response):
    """Submission row: preserve identity + predicted_track_ids, replace
    predicted_response. Drops any extra fields so the output matches the
    validator's expected schema exactly."""
    return {
        "session_id": pred_row["session_id"],
        "user_id": pred_row["user_id"],
        "turn_number": pred_row["turn_number"],
        "predicted_track_ids": pred_row["predicted_track_ids"],
        "predicted_response": new_response,
    }


def _is_rate_limited(err_str):
    es = err_str.lower()
    return ("429" in err_str or "resourceexhausted" in es
            or "quota" in es or "exhausted" in es)


def generate_response(model, prompt, fallback, max_attempts=6,
                      sleep_fn=time.sleep, parse_fn=None):
    """Call Gemini with retry/backoff on rate limits. Returns the stripped
    reply text, or `fallback` (the row's original response) if every attempt
    fails — we never drop a row's response. A blocked/empty candidate (whose
    `.text` accessor raises) is non-retryable and falls back.

    `parse_fn` (used by --structured) post-processes the raw model text into the
    final reply; if it returns a falsy value (e.g. unparseable JSON) we fall back
    rather than submit the raw text."""
    for attempt in range(max_attempts):
        try:
            resp = model.generate_content(prompt)
            raw = resp.text or ""
            text = parse_fn(raw) if parse_fn else raw.strip()
            return text if text else fallback
        except Exception as e:  # noqa: BLE001 — API raises a variety of types
            es = str(e)
            if _is_rate_limited(es) and attempt < max_attempts - 1:
                m = re.search(r"retry in ([\d.]+)s", es)
                wait = (float(m.group(1)) + 1.0) if m else min(60.0, 5.0 * (attempt + 1))
                print(f"  rate-limited, waiting {wait:.0f}s (attempt {attempt+1}/{max_attempts})")
                sleep_fn(wait)
            else:
                print(f"  API error, keeping original response: {e!r}")
                return fallback
    return fallback


def _load_item_meta():
    import datasets as _d
    from datasets import load_dataset
    idb = load_dataset(ITEM_DB)
    idb = _d.concatenate_datasets([idb[s] for s in idb])
    meta = {}
    for r in idb:
        meta[str(r["track_id"])] = {
            "track_name": r.get("track_name"),
            "artist_name": r.get("artist_name"),
            "album_name": r.get("album_name"),
            "tags": r.get("tag_list"),
        }
    return meta


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pred", required=True, help="existing prediction.json (keeps predicted_track_ids)")
    ap.add_argument("--out", required=True, help="output prediction.json with regenerated responses")
    ap.add_argument("--dataset", default=DEFAULT_DATASET, help="HF dataset for conversation context (split=test)")
    ap.add_argument("--top-n", type=int, default=1, help="how many reranked tracks the responder sees")
    ap.add_argument("--limit", type=int, default=0, help="cap rows (0 = all)")
    ap.add_argument("--sleep", type=float, default=0.2, help="seconds between API calls")
    ap.add_argument("--structured-personality", action="store_true",
                    help="structured_personality (CoT) mode: the model fills personalization axes "
                         "(mood/intent/energy/sonic_pref/era_pref/familiarity) + a per-axis track "
                         "'fit' before writing; only the JSON `reply` is submitted")
    args = ap.parse_args()

    if args.top_n < 1:
        sys.exit("ERROR: --top-n must be >= 1 (the responder needs at least one track to explain).")
    key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not key:
        sys.exit("ERROR: set GEMINI_API_KEY (Colab secret) before running.")
    import google.generativeai as genai
    from datasets import load_dataset
    genai.configure(api_key=key)
    model = genai.GenerativeModel(MODEL)

    preds = json.load(open(args.pred))
    if args.limit:
        preds = preds[: args.limit]
    mode = "structured_personality" if args.structured_personality else "plain"
    print(f"[responder] {len(preds)} rows from {args.pred} via {MODEL} "
          f"(top_n={args.top_n}, mode={mode})")

    ds = load_dataset(args.dataset, split="test")
    sess_by_id = {s["session_id"]: s for s in ds}
    item_db_meta = _load_item_meta()

    out_rows, n_gen, n_fallback = [], 0, 0
    for i, p in enumerate(preds):
        # Per-row guard: a single malformed session (unexpected schema, missing
        # conversations, bad goal shape) falls back to the original response
        # instead of aborting the whole run. Row count is always conserved.
        fallback = p.get("predicted_response", "") or ""
        try:
            sess = sess_by_id.get(p["session_id"])
            if sess is None:
                new_resp = fallback
            else:
                ctx = render_context(sess["conversations"], item_db_meta, p["turn_number"])
                tracks = format_tracks(p.get("predicted_track_ids"), item_db_meta, n=args.top_n)
                goal = ((sess.get("conversation_goal") or {}).get("listener_goal") or "").strip()
                if args.structured_personality:
                    prompt = build_structured_prompt(ctx, tracks, goal)
                    new_resp = generate_response(model, prompt, fallback,
                                                 parse_fn=parse_structured_reply)
                else:
                    prompt = build_prompt(ctx, tracks, goal)
                    new_resp = generate_response(model, prompt, fallback)
        except Exception as e:  # noqa: BLE001 — never let one row kill the run
            print(f"  row {i} ({p.get('session_id')}): error, keeping original response: {e!r}")
            new_resp = fallback
        if new_resp == fallback:
            n_fallback += 1
        else:
            n_gen += 1
        out_rows.append(build_output_row(p, new_resp))
        if args.sleep:
            time.sleep(args.sleep)
        if (i + 1) % 25 == 0:
            print(f"  {i+1}/{len(preds)} (generated={n_gen}, fallback={n_fallback})")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    json.dump(out_rows, open(args.out, "w"), ensure_ascii=False)
    print(f"\n[responder] wrote {len(out_rows)} rows -> {args.out} "
          f"(generated={n_gen}, fallback={n_fallback})")


if __name__ == "__main__":
    main()
