"""Regenerate predicted_response with the Gemini API (responder-side twin of
scripts/gemini_judge_responses.py).

Takes an existing prediction.json — whose predicted_track_ids were produced by
the retrieval+rerank pipeline — rejoins each row to its conversation context +
the recommended tracks' metadata, and rewrites predicted_response via Gemini.
predicted_track_ids are left UNTOUCHED (this only swaps the LLM/response axis).
The output is a new prediction.json with the same rows, ready to validate +
submit (scripts/validate_prediction.py).

Why this exists: the challenge scores predicted_response with a Gemini judge on
Personalization + Explanation Quality (0.30 of the composite). The static
prediction.json carries no model provenance, so the response text may be
generated by any method. See project_responder_topn_ab_status_2026_06_04 memory
for the rules check (no rule bans external APIs; final code-upload required;
judge family is Gemini -> self-preference risk) and the top_n A/B (the local
v5-kto responder is best at top_n=1 because it was trained on a single grounded
track — that is responder-specific, NOT assumed to carry to Gemini).

Usage:
    GEMINI_API_KEY=...  python scripts/gemini_responder.py \
        --pred exp/inference/blindset_A/<tid>.json \
        --out  exp/inference/blindset_A/<tid>_gemini.json \
        --top-n 1
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from pathlib import Path

import pandas as pd

MODEL = os.environ.get("GEMINI_RESPONDER_MODEL", "gemini-2.5-flash")
# A 2-3 sentence reply (or a small JSON in structured mode) needs only a few
# hundred tokens; the cap is a runaway guard, NOT a latency knob (unused tokens
# cost nothing). With thinking off it never truncates a real reply.
MAX_OUTPUT_TOKENS = int(os.environ.get("GEMINI_MAX_OUTPUT_TOKENS", "1024"))
# 0 = thinking DISABLED. The gemini-2.5 models otherwise spend their whole output
# budget "thinking" and return finish_reason=STOP with NO answer Part, so `.text`
# raises and every row falls back. Disabling it both fixes that and is far faster.
THINKING_BUDGET = int(os.environ.get("GEMINI_THINKING_BUDGET", "0"))


class GenModel:
    """Adapter exposing the legacy `model.generate_content(prompt, generation_config=...)`
    surface on top of the modern google-genai client, with THINKING DISABLED and a hard
    `max_output_tokens` cap. This is the fix for the gemini-2.5 failure where the model
    spends its whole budget thinking, returns finish_reason=STOP with no answer Part, and
    `.text` raises (-> every row fell back). thinking_budget=0 is valid for flash /
    flash-lite; pro cannot fully disable thinking, so a 0 is clamped to its 128 minimum.

    Keeping this surface identical to the old genai.GenerativeModel means _call_model /
    generate_response / generate_best_of_n and all their tests are untouched."""

    def __init__(self, client, types, model, max_output_tokens=MAX_OUTPUT_TOKENS,
                 thinking_budget=THINKING_BUDGET):
        self.client, self.types, self.model = client, types, model
        self.max_output_tokens = max_output_tokens
        # pro can't run with a 0 budget; bump a requested 0 to the 128 floor for it.
        self.thinking_budget = (128 if thinking_budget == 0 and "pro" in model.lower()
                                else thinking_budget)

    def generate_content(self, prompt, generation_config=None):
        gc = generation_config or {}
        t = self.types
        cfg = t.GenerateContentConfig(
            max_output_tokens=self.max_output_tokens,
            temperature=gc.get("temperature"),
            thinking_config=t.ThinkingConfig(thinking_budget=self.thinking_budget),
        )
        return self.client.models.generate_content(
            model=self.model, contents=prompt, config=cfg)


def _resp_cache_path(cache_dir: str, prompt: str, model: str, best_of: int,
                     cache_salt: str = "") -> Path:
    """Cache key = (prompt, model, best_of, cache_salt). The prompt already encodes ctx
    + the rendered tracks + goal + top_n + plain/structured mode; best_of changes
    generation. cache_salt carries the generation knobs the prompt does NOT encode
    (thinking_budget, temperature config) — without it a thinking/temp retune reads
    STALE replies from a warm cache and an A/B looks flat (bug #10)."""
    key = "\n".join([prompt, str(model), str(best_of), str(cache_salt)])
    h = hashlib.sha1(key.encode("utf-8")).hexdigest()[:24]
    return Path(cache_dir) / f"{h}.json"


def load_reuse_map(path) -> dict:
    """Map {(session_id, turn_number): {'ids': [...], 'resp': str}} from a PRIOR
    prediction.json — to warm-start responses so only changed rows hit Gemini.
    Accepts a .json file OR a .zip (reads its `prediction.json` member, e.g. a saved
    submission on Drive). Missing / empty path -> {}."""
    if not path:
        return {}
    if str(path).endswith(".zip"):
        import zipfile
        with zipfile.ZipFile(path) as z:
            member = next((n for n in z.namelist() if n.endswith("prediction.json")), None)
            if member is None:
                raise ValueError(f"{path}: no prediction.json inside the zip")
            rows = json.loads(z.read(member))
    else:
        with open(path, encoding="utf-8") as f:
            rows = json.load(f)
    m: dict = {}
    for r in rows:
        m[(r.get("session_id"), r.get("turn_number"))] = {
            "ids": r.get("predicted_track_ids") or [],
            "resp": r.get("predicted_response") or "",
        }
    return m


def reuse_response(reuse_map: dict, session_id, turn_number, track_ids, top_n: int):
    """Prior response IFF the responder-visible tracks (the top_n shown) are unchanged
    vs the prior run, else None. ctx + goal are deterministic from (session_id,
    turn_number), so identical shown-tracks => identical responder input => safe reuse.
    (Pass a reuse file produced by the SAME responder config: model / top_n / best_of.)"""
    prior = reuse_map.get((session_id, turn_number))
    if not prior or not prior["resp"]:
        return None
    if list(prior["ids"][:top_n]) == list((track_ids or [])[:top_n]):
        return prior["resp"]
    return None


def cached_response(cache_dir, prompt: str, model: str, best_of: int,
                    gen_fn, fallback: str, cache_salt: str = "") -> str:
    """Disk-cache the responder output so reruns don't re-pay Gemini. `gen_fn()`
    returns the freshly generated response. A FALLBACK (generation failed -> kept
    the original) is NOT cached, so a fixed API/key regenerates next run (the same
    rule the listwise reranker uses for empty parses). cache_dir falsy -> no cache.
    cache_salt keys generation knobs not in the prompt (thinking_budget/temperature)
    so a retune doesn't read stale replies (bug #10)."""
    cp = None
    if cache_dir:
        cp = _resp_cache_path(cache_dir, prompt, model, best_of, cache_salt)
        if cp.exists():
            try:
                return json.loads(cp.read_text(encoding="utf-8"))["response"]
            except (OSError, json.JSONDecodeError, KeyError, ValueError):
                pass
    resp = gen_fn()
    if cp is not None and resp and resp != fallback:
        cp.parent.mkdir(parents=True, exist_ok=True)
        cp.write_text(json.dumps({"response": resp}, ensure_ascii=False),
                      encoding="utf-8")
    return resp
# best-of-N judge: cheaper/faster model scores candidates (generate with the
# strong responder model, judge with this one to keep cost down).
JUDGE_MODEL = os.environ.get("GEMINI_JUDGE_MODEL", "gemini-2.5-flash")
DEFAULT_TEMPS = (0.5, 0.8, 1.0)  # cycled across best-of-N candidates for diversity
DEFAULT_DATASET = "talkpl-ai/TalkPlayData-Challenge-Dataset"
ITEM_DB = "talkpl-ai/TalkPlayData-Challenge-Track-Metadata"

RESPONDER_INSTRUCTIONS = """You are an expert music recommender replying to a user mid-conversation.
Write ONE reply, 2-3 short sentences, no lists, no preamble. Return ONLY the reply text — no labels or headers.

VOICE & MOOD: warm and genuine, like a friend with great taste — never a salesperson. Match the user's mood,
energy, and SITUATION in your wording and pace: going for a run or working out → vibrant and punchy; winding
down, studying, or relaxing → calm and unhurried; partying or hyped → bring the energy; heartbroken or
reflective → gentle. Mirror their register: a short, direct user gets a short, direct reply; a chatty user
can get a touch warmer. The reply should FEEL like the moment they're in.

ANSWER THE LATEST MESSAGE: reply directly to what the user just asked — on point, not a generic pitch.
Recommend the SINGLE best-fitting track from the candidates and build the reply around it; add a second only
if it genuinely fits the same request (never on a shallow coincidence like a shared word in the title).

PERSONALIZATION: echo ONE specific thing the user actually named — the track or artist they said they liked,
or a concrete descriptor they used — and quote or closely paraphrase it. Do NOT restate the abstract listener
goal as the personalization ("you want to discover new artists" is too generic), and NEVER frame the pick as
filling a task/goal/genre SLOT — banned: "a fitting track for general recommendations", "in the genre you
asked for", "fits your goal of …", "for general recommendations in the genre"; name the concrete shared trait
instead. If earlier in the
conversation the user liked a track, you MUST name that earlier track and connect your pick to it through a
real shared trait; steer away from anything they rejected, and never invent a past preference.
With no prior history (cold start), personalize from the user's current request and stated goal — the mood,
activity, and qualities they just named.

EXPLANATION: justify the pick with at least one CONCRETE, checkable attribute, drawn ONLY from what you were
given. Citeable types: artist, title, album, genre/tags, mood, instrumentation, era. Be specific, not vibe-soup:
  GOOD: "built on a walking bassline and brushed drums" / "opens on a lone piano before the strings swell"
  WEAK (avoid): "has a great chill vibe" / "energetic, soulful energy" / "intense, driving sound" /
    "delivers intense, focused hip-hop" / "that upbeat electronic energy" (name the beat/synth/riff/production instead)
NEVER make reception, popularity, chart, or critical-acclaim claims — they are NOT in the data and read as
guesses (and risk being wrong). Banned: "fan favorite", "beloved", "iconic", "classic", "a standout", "one of
the best", "everyone loves", "quintessential", and any chart position, award, or critic mention.
Describe ONLY the music (sound, instruments, rhythm, mood, genre, era) — NEVER the album art, cover,
packaging, artwork, or any visual; if you have no real sonic detail, say less rather than invent one.

VARY YOUR OPENING — rotate between these shapes, and never repeat one back-to-back:
  (a) name the track + one concrete trait;  (b) echo the exact track/artist the user named, then pivot to the pick;
  (c) name the artist as the bridge;  (d) open on the standout musical detail (the riff, the beat, the voice);
  (e) answer their exact question head-on.
Never open with "For …", "Since …", "Absolutely", or "Yes".

TONE: cut empty intensifiers — at most ONE in the whole reply, never as the opener: absolutely, truly,
definitely, literally, really, simply, perfectly, incredible, captivating, amazing, fantastic, wonderfully,
deeply, perfect. No exclamation-mark openers. And drop the "that [vibe] you're after / you're looking for"
crutch — name the concrete thing instead (say "that stop-start funk riff", not "that energy you're after")."""


# Hard constraints, restated as a short checklist placed at the VERY END of the prompt (after the tracks) —
# recency lifts compliance far more than the same rules buried in the prose block above.
FINAL_CHECKLIST = """=== CHECK BEFORE YOU REPLY ===
1. Name ONE specific track from the candidates and say why it fits.
2. Cite at least one CONCRETE musical attribute you were given. NEVER state reception/popularity or any checkable external fact NOT in the data — no "iconic/classic/beloved/legendary", and absolutely no chart/award/sales/iTunes/"one of the best" claims (these are hallucinations and are penalized hard). NO album-art/visual mentions.
3. Echo one specific thing the user said — and the earlier liked track BY NAME if the conversation has one. Never frame the pick as filling a task/goal/genre slot ("for general recommendations", "in the genre you asked for").
4. Do NOT open with "Since …/For …/Yes/Absolutely/Sure" — start mid-scene on the track itself, a musical detail (the riff/beat/voice), or the user's exact words. Vary the shape from the last reply.
5. At most one intensifier (no "definitely/truly/perfectly/really/absolutely"); no "you're looking for / after" crutch; no exclamation-mark opener.
6. 2-3 tight sentences; output the reply text only."""


def _first(v):
    """HF metadata fields are often singleton lists; unwrap to a scalar."""
    if isinstance(v, list):
        return v[0] if v else None
    return v


def _track_inline(meta):
    """One-line 'Name by Artist — tag1, tag2' for a prior in-session rec, so the
    model can connect a new pick to what the user already liked via shared traits."""
    name = _first(meta.get("track_name"))
    artist = _first(meta.get("artist_name"))
    tags = meta.get("tags") or meta.get("tag_list") or []
    tags = tags if isinstance(tags, list) else [str(tags)]
    s = f"{name} by {artist}"
    if tags:
        s += f" — {', '.join(str(x) for x in tags[:4])}"
    return s


def render_context(conversations, item_db_meta, target_turn):
    """Render the user-visible conversation up to (and including) the target
    user turn. Music turns are expanded to the recommended track's name AND its
    attributes (so the reply can build continuity from what the user liked); the
    target turn's own assistant/music reply is excluded (that is what we are
    generating)."""
    df = pd.DataFrame(conversations)
    lines = []
    hist = df[df["turn_number"] < target_turn]
    for _, t in hist.iterrows():
        role = t["role"]
        content = t["content"]
        if role == "music":
            role = "assistant"
            m = item_db_meta.get(str(content), {})
            content = f"[recommended: {_track_inline(m)}]"
        lines.append(f"{role}: {content}")
    cur = df[(df["turn_number"] == target_turn) & (df["role"] == "user")]
    if len(cur):
        lines.append(f"user: {cur.iloc[0]['content']}")
    return "\n".join(lines)


def format_tracks(tids, item_db_meta, n=1):
    """Format the top-n recommended tracks (cleaned tag list) as grounding for the reply.
    Skips ids with no metadata (never emits a bare 'None by None')."""
    out = []
    for tid in (tids or [])[:n]:
        m = item_db_meta.get(str(tid))
        if not m:
            continue
        name = _first(m.get("track_name"))
        artist = _first(m.get("artist_name"))
        if name is None and artist is None:
            continue
        tags = m.get("tags") or m.get("tag_list") or []
        tags = tags if isinstance(tags, list) else [str(tags)]
        part = f"{name} by {artist}"
        album = _first(m.get("album_name"))
        if album:
            part += f" (album {album})"
        if tags:
            part += f" [{', '.join(str(x) for x in tags[:5])}]"
        out.append(part)
    return "; ".join(out) if out else "(none)"


# Few-shot style references. REAL tracks + REAL user requests curated from the
# TalkPlayData train set's high-GPA turns (the dataset gold is noisy/often
# misaligned, so these were hand-verified for alignment and trimmed of generic
# filler openers). Each models the target pattern: answer the latest message,
# lead with ONE best-fit track, tie it to what the user said, cite a concrete
# attribute, natural tone. Labeled "do not reuse" so the model copies STYLE,
# not these example tracks.
FEW_SHOT_EXAMPLES = """=== EXAMPLES (style reference only — do not reuse these tracks; each opens a different way) ===
[user]: I love 'With A Little Help From My Friends' — that collaborative, Sgt. Pepper's-era feel. Could you suggest another Beatles track from around 1967, something that showcases their more psychedelic, artistic side?
[tracks]: Strawberry Fields Forever by The Beatles [psychedelic, 1967, mellotron, dreamy, experimental]
[reply]: "Strawberry Fields Forever" is the Beatles at their most experimental in 1967 — a hazy mellotron drifting under a dreamy, slowed-down melody. It keeps the Sgt. Pepper's-era feel of "With A Little Help From My Friends" but leans fully into the psychedelic side you asked about.

[user]: This is exactly what I wanted — a beautiful, piano-focused jazz track. Got any more like it?
[tracks]: Lucky To Be Me by Bill Evans [jazz, piano, ballad, mellow, introspective]
[reply]: Bill Evans is the pianist to stay with — "Lucky To Be Me" is a slow, introspective ballad carried by his spare piano and the space he leaves between the notes. It's the same piano-focused jazz you just enjoyed, stripped right down to the touch.

[user]: "Dog Days Are Over" is exactly the vivid, dramatic storytelling I was hoping for — that emotional intensity is perfect. More like this?
[tracks]: Cosmic Love by Florence + The Machine [dramatic, baroque pop, harp, big drums, powerful vocals]
[reply]: You loved the drama of "Dog Days Are Over," so go to "Cosmic Love" — it opens on a delicate harp, then drops into pounding drums and Florence's full-belt vocal. Same vivid, building storytelling, just darker."""


def build_prompt(context, tracks_str, listener_goal):
    """Assemble the responder prompt from the rubric instructions, few-shot style
    examples, the conversation, the recommended tracks, and (optionally) the goal."""
    parts = [RESPONDER_INSTRUCTIONS, "", FEW_SHOT_EXAMPLES,
             "", "=== CONVERSATION ===", context]
    if listener_goal:
        parts += ["", f"Listener goal: {listener_goal}"]
    parts += ["", "=== RECOMMENDED TRACK(S) TO PRESENT ===", tracks_str,
              "", FINAL_CHECKLIST, "", "Reply:"]
    return "\n".join(parts)


STRUCTURED_INSTRUCTIONS = """You are an expert music recommender. FIRST analyze the user, THEN reply.

Return ONLY a JSON object with exactly these keys:
{
  "user_state": {"mood": "...", "intent": "...", "energy": "...", "sonic_pref": "...",
                 "era_pref": "...", "familiarity": "..."},
  "fit": "...",
  "reply": "..."
}

- user_state: infer each axis from the conversation; use "unknown" for any axis the user did not signal.
  This is PRIVATE reasoning to guide the reply — it is never shown to the user.
- fit: for each axis that matters, name the concrete attribute of the recommended track(s) that satisfies it.
- reply: the final message to send the user. It MUST:
    * directly answer the user's MOST RECENT message and what they actually asked for — the reply has to
      read as an on-point response to that request, not a description of your analysis;
    * ground personalization ONLY in preferences the user explicitly stated in the conversation; do NOT
      present inferred guesses about their mood/taste as if they were facts the user told you;
    * cite ONLY attributes that appear in the RECOMMENDED TRACK(S) block; if an attribute is not listed
      there, do not mention it and do not invent it;
    * be 2-3 natural sentences, no lists, no preamble, and must NOT mention these JSON keys or your analysis;
    * never be generic and never over-claim — if you are unsure of something, leave it out rather than
      guess, so nothing in the reply sounds made up.

Output ONLY the JSON object."""


def build_structured_prompt(context, tracks_str, listener_goal):
    """CoT-style prompt: the model fills personalization axes + a per-axis track
    'fit' (hidden scaffolding) before writing the final `reply`. Only `reply` is
    submitted (see parse_structured_reply)."""
    parts = [STRUCTURED_INSTRUCTIONS, "", "=== CONVERSATION ===", context]
    if listener_goal:
        parts += ["", f"Listener goal: {listener_goal}"]
    parts += ["", "=== RECOMMENDED TRACK(S) TO PRESENT ===", tracks_str, "", "JSON:"]
    return "\n".join(parts)


def parse_structured_reply(text):
    """Extract the `reply` string from the model's JSON output. Returns None if
    it can't be parsed or `reply` is missing/empty — the caller then falls back
    (we never submit raw JSON as the response)."""
    if not text:
        return None
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        return None
    blob = m.group(0)
    try:
        d = json.loads(blob)
        reply = d.get("reply") if isinstance(d, dict) else None
        if isinstance(reply, str) and reply.strip():
            return reply.strip()
        return None
    except Exception:
        # Tolerate trailing junk / minor malformation: grab the reply value directly.
        # Use the LAST match so a nested decoy `reply` (e.g. inside user_state)
        # doesn't win over the real top-level one.
        rms = re.findall(r'"reply"\s*:\s*"((?:[^"\\]|\\.)*)"', blob, re.DOTALL)
        if not rms:
            return None
        captured = rms[-1]
        try:
            val = json.loads('"' + captured + '"')
        except Exception:
            val = captured
        val = val.strip()
        return val or None


def build_output_row(pred_row, new_response):
    """Submission row: preserve identity + predicted_track_ids, replace
    predicted_response. Drops any extra fields so the output matches the
    validator's expected schema exactly."""
    return {
        "session_id": pred_row["session_id"],
        "user_id": pred_row["user_id"],
        "turn_number": pred_row["turn_number"],
        "predicted_track_ids": pred_row["predicted_track_ids"],
        "predicted_response": new_response,
    }


def _is_rate_limited(err_str):
    es = err_str.lower()
    return ("429" in err_str or "resourceexhausted" in es
            or "quota" in es or "exhausted" in es)


def _call_model(model, prompt, sleep_fn=time.sleep, max_attempts=6, gen_config=None):
    """Raw Gemini call with retry/backoff on rate limits. Returns the raw text,
    or None if every attempt fails (rate-limit exhausted, API error, or a
    blocked/empty candidate whose `.text` accessor raises)."""
    for attempt in range(max_attempts):
        try:
            kw = {"generation_config": gen_config} if gen_config else {}
            resp = model.generate_content(prompt, **kw)
            return resp.text or ""
        except Exception as e:  # noqa: BLE001 — API raises a variety of types
            es = str(e)
            if _is_rate_limited(es) and attempt < max_attempts - 1:
                m = re.search(r"retry in ([\d.]+)s", es)
                wait = (float(m.group(1)) + 1.0) if m else min(60.0, 5.0 * (attempt + 1))
                print(f"  rate-limited, waiting {wait:.0f}s (attempt {attempt+1}/{max_attempts})")
                sleep_fn(wait)
            else:
                print(f"  API error: {e!r}")
                return None
    return None


def generate_response(model, prompt, fallback, max_attempts=6,
                      sleep_fn=time.sleep, parse_fn=None):
    """Single-shot reply. Returns the stripped reply text, or `fallback` (the
    row's original response) if the call fails or yields empty/unparseable text
    — we never drop a row's response.

    `parse_fn` (used by --structured-personality) post-processes the raw text;
    if it returns a falsy value we fall back rather than submit raw text."""
    raw = _call_model(model, prompt, sleep_fn=sleep_fn, max_attempts=max_attempts)
    if raw is None:
        return fallback
    text = parse_fn(raw) if parse_fn else raw.strip()
    return text if text else fallback


JUDGE_INSTRUCTIONS = """Score a music recommender's reply to a user on TWO axes, 0-5 each.
PERSONALIZATION: does the reply reflect THIS user's stated intent, mood, and taste? 5 = clearly tailored to them; 0 = generic.
EXPLANATION_QUALITY: does it give a concrete, accurate reason citing real attributes of the recommended track? 5 = specific and grounded; 0 = vague or hallucinated.
Return ONLY a JSON object: {"personalization": <0-5>, "explanation_quality": <0-5>}"""


def build_judge_prompt(context, tracks_str, reply):
    """Prompt the judge model to score one candidate reply on the two axes."""
    return (f"{JUDGE_INSTRUCTIONS}\n\n=== CONVERSATION ===\n{context}\n\n"
            f"=== RECOMMENDED TRACKS ===\n{tracks_str}\n\n"
            f"=== REPLY TO SCORE ===\n{reply}\n\nReturn only the JSON.")


def parse_judge_score(text):
    """Sum of personalization + explanation_quality from the judge JSON; None if
    unparseable or an axis is missing (so unscored candidates rank last)."""
    if not text:
        return None
    m = re.search(r"\{[^{}]*\}", text, re.DOTALL)
    if not m:
        return None
    try:
        d = json.loads(m.group(0))
        return float(d["personalization"]) + float(d["explanation_quality"])
    except Exception:
        return None


def pick_best(scored):
    """`scored`: list of (reply, score|None). Return the reply with the highest
    score; if no candidate was scored, return the first reply; [] -> None."""
    if not scored:
        return None
    real = [(r, s) for r, s in scored if s is not None]
    if real:
        return max(real, key=lambda rs: rs[1])[0]
    return scored[0][0]


# ── anti-pattern guard (fix 1) + reception teeth (fix 3) ───────────────────────
# The 2026-06-21 Blind-A judge analysis: 35% of replies opened "Since you …", 35%
# used the "you're looking for" crutch, and several made hallucinated reception
# claims — all already banned in the prompt, which the model obeyed only ~65% of
# the time. The guard scores each best-of candidate by banned-pattern count and
# prefers the cleanest, so compliance is enforced by SELECTION, not the prose rules.
_BANNED_OPENER = re.compile(r'^\s*["\']?\s*(for|since|yes|absolutely|sure)\b', re.I)
_CRUTCH = re.compile(r"you('?re| are)\s+(looking for|after|seeking|in the mood for|craving)", re.I)
_RECEPTION = re.compile(
    r"\b(iconic|classic|fan[- ]fav(?:ou?rite|orite)|beloved|quintessential|standout|"
    r"legendary|timeless|acclaimed|everyone loves)\b", re.I)
# Strong reception = invented, checkable facts not in the catalog -> the worst judge hit; penalized twice.
_RECEPTION_STRONG = re.compile(
    r"\b(chart(?:-topping|ed)?|billboard|grammy|platinum|gold record|best[- ]selling|itunes|"
    r"award[- ]winning|massive hit|number one|#1|one of the best|sold .* copies|critically acclaimed)\b", re.I)
_ALBUM_ART = re.compile(r"\b(album art|cover art|artwork|album cover|the cover|packaging|visual)\b", re.I)
_INTENS = re.compile(
    r"\b(absolutely|truly|definitely|literally|really|simply|perfectly|incredible|captivating|"
    r"amazing|fantastic|wonderfully|deeply|perfect)\b", re.I)


def count_violations(reply: str) -> int:
    """Count banned-pattern violations in a candidate reply (higher = worse). Covers
    the prompt's hard rules: banned opener (For/Since/Yes/Absolutely/Sure), the
    "you're looking for" crutch, reception/popularity words (hallucinated-fact ones
    penalized twice), album-art/visual mentions, an exclamation-mark opener, and
    >=2 intensifiers. Empty -> 0 (the fallback path handles emptiness)."""
    if not reply or not reply.strip():
        return 0
    r = reply.strip()
    v = 0
    if _BANNED_OPENER.match(r):
        v += 1
    if _CRUTCH.search(r):
        v += 1
    if _RECEPTION.search(r):
        v += 1
    if _RECEPTION_STRONG.search(r):
        v += 2                                    # invented, checkable reception is the worst failure
    if _ALBUM_ART.search(r):
        v += 1
    if re.match(r"^[^.!?]*!", r):                  # exclamation before the first sentence ends
        v += 1
    if len(_INTENS.findall(r)) >= 2:
        v += 1
    return v


def select_best(scored, penalty_fn=count_violations):
    """`scored`: list of (reply, judge_score|None). Pick the reply with the FEWEST
    rule violations, tie-broken by highest judge score (an unscored candidate ranks
    last among equals). [] -> None. This makes selection robust even when the judge
    fails: a cleaner reply still wins on violations alone."""
    if not scored:
        return None
    def key(rs):
        r, s = rs
        return (penalty_fn(r), -(s if s is not None else float("-inf")))
    return min(scored, key=key)[0]


def generate_best_of_n(gen_model, judge_model, prompt, judge_context, tracks_str,
                       fallback, n, temperatures, sleep_fn=time.sleep, parse_fn=None):
    """Generate n candidate replies (varied temperature), score each with the
    judge model on the rubric, and return the highest-scoring. Falls back to the
    row's original response if no candidate is produced."""
    cands = []
    for i in range(max(1, n)):
        t = temperatures[i % len(temperatures)]
        raw = _call_model(gen_model, prompt, sleep_fn=sleep_fn,
                          gen_config={"temperature": t})
        if raw is None:
            continue
        reply = parse_fn(raw) if parse_fn else raw.strip()
        if reply:
            cands.append(reply)
    if not cands:
        return fallback
    if len(cands) == 1:
        return cands[0]
    scored = []
    for r in cands:
        jraw = _call_model(judge_model, build_judge_prompt(judge_context, tracks_str, r),
                          sleep_fn=sleep_fn)
        scored.append((r, parse_judge_score(jraw)))
    # guard: fewest banned-pattern violations first, judge score as tie-breaker.
    return select_best(scored, count_violations)


# ── tag cleaning ──────────────────────────────────────────────────────────────
# TalkPlayData tag_list is last.fm-style folksonomy: real musical descriptors (genre/mood/instrument/era)
# mixed with junk — ratings ("8 of 10 stars"), playlist names ("ion b chill station"), opinions
# ("favorites", "awesome"), sentences ("songs i absolutely love"), and other-artist names. Feeding the raw
# list tempts ungrounded/generic explanations; we keep a diverse set of concrete descriptors and drop junk.
_TAG_MOODS = frozenset({
    "chill", "mellow", "relaxing", "energetic", "upbeat", "dark", "melancholic", "melancholy", "dreamy",
    "atmospheric", "aggressive", "soothing", "uplifting", "haunting", "romantic", "sad", "happy", "epic",
    "smooth", "groovy", "moody", "intense", "soft", "calm", "peaceful", "ethereal", "nostalgic", "hypnotic",
    "driving", "anthemic", "raw", "gentle", "bittersweet", "euphoric", "brooding", "funky", "chillout",
    "laid-back", "danceable", "emotional", "powerful", "melodic", "lo-fi", "catchy", "spacey", "trippy"})
_TAG_INSTR = frozenset({
    "piano", "guitar", "bass", "drums", "synth", "synths", "strings", "saxophone", "sax", "violin", "organ",
    "acoustic guitar", "electric guitar", "brass", "flute", "trumpet", "cello", "harp", "percussion",
    "acoustic", "instrumental", "female vocalists", "male vocalists", "female vocalist", "male vocalist"})
_TAG_STOP = frozenset({
    "favorites", "favorite", "favourites", "favourite", "fav", "favs", "love", "loved", "awesome", "good",
    "cool", "nice", "great", "amazing", "best", "beautiful", "perfect", "wonderful", "masterpiece", "music",
    "seen live", "top quality", "killer", "owned", "wishlist", "all", "various", "misc", "stuff", "heard",
    "genius", "american", "british", "usa", "uk", "sexy", "sex", "cap", "body parts", "life is easy", "good music"})
_TAG_NORM = {"male vocalist": "male vocals", "male vocalists": "male vocals",
             "female vocalist": "female vocals", "female vocalists": "female vocals"}
_TAG_DROP_RE = re.compile(r"\bstars?\b|\d+ of \d+|^\d+$|\bvia\b|\bi\b|\bmy\b|\bme\b|wishlist|tagme|^\W")
_TAG_ERA_RE = re.compile(r"^(19|20)\d0s?$|^\d0s$")


def clean_tags(tags, df, artists, track_name, artist_name, keep=8):
    """Filter a raw tag_list down to concrete musical descriptors. `df` = {tag: doc-frequency across the
    catalog} (long-tail junk like playlist names is rare -> dropped via a min-frequency floor); `artists` =
    set of lowercased artist names (drops 'similar artist' tags). Returns a diverse, specific mix — genres
    (specific first), moods, instruments, era — with ratings/opinions/self-references removed."""
    nm = set(re.findall(r"\w+", (str(track_name) + " " + str(artist_name)).lower()))
    seen, genres, moods, instr, era = set(), [], [], [], []
    for t in (tags or []):
        sl = str(t).strip().lower()
        if not sl or sl in seen or sl in _TAG_STOP or _TAG_DROP_RE.search(sl) or len(sl.split()) > 4:
            continue
        toks = set(re.findall(r"\w+", sl))
        if (toks and toks <= nm) or (sl in artists and sl not in nm):   # self-name / other-artist tag
            continue
        seen.add(sl)
        if _TAG_ERA_RE.match(sl):
            era.append(sl)
        elif sl in _TAG_INSTR:
            instr.append((_TAG_NORM.get(sl, sl), df.get(sl, 0)))
        elif sl in _TAG_MOODS:
            moods.append((sl, df.get(sl, 0)))
        elif df.get(sl, 0) >= 30:                                       # genre-ish: common enough to be real
            genres.append((sl, df.get(sl, 0)))
    genres.sort(key=lambda x: (-(" " in x[0]), -x[1]))                  # prefer specific (multi-word) genres
    out, s = [], set()
    for t in ([g for g, _ in genres[:3]]
              + [m for m, _ in sorted(moods, key=lambda x: -x[1])[:2]]
              + [i for i, _ in sorted(instr, key=lambda x: -x[1])[:2]]
              + era[:1]):
        if t not in s:
            out.append(t); s.add(t)
    return out[:keep]


def _load_item_meta():
    import collections
    import datasets as _d
    from datasets import load_dataset
    idb = load_dataset(ITEM_DB)
    idb = _d.concatenate_datasets([idb[s] for s in idb])
    # global tag doc-frequency + artist-name set, used by clean_tags to drop long-tail junk + artist tags
    df, artists = collections.Counter(), set()
    for r in idb:
        for t in {str(x).strip().lower() for x in (r.get("tag_list") or [])}:
            if t:
                df[t] += 1
        a = _first(r.get("artist_name"))
        if a:
            artists.add(str(a).strip().lower())
    meta = {}
    for r in idb:
        meta[str(r["track_id"])] = {
            "track_name": r.get("track_name"),
            "artist_name": r.get("artist_name"),
            "album_name": r.get("album_name"),
            "tags": clean_tags(r.get("tag_list"), df, artists,
                               _first(r.get("track_name")), _first(r.get("artist_name"))),
        }
    return meta


def summarize_run(n_gen: int, n_reused: int, fallback_sids: list, total: int,
                  fail_on_fallback: bool) -> dict:
    """Post-run report + abort decision. A 'fallback' row kept its ORIGINAL
    predicted_response (no fresh Gemini output, no warm-start reuse). When the
    input came from run_inference_blindset --retrieval_only, that original IS the
    literal 'ok' stub, which scores ~1/5 on the LLM axis (the config-209
    regression). Returns {ok, exit_code, messages}. Pure -> unit-tested."""
    msgs: list[str] = []
    n_fb = len(fallback_sids)
    if n_gen == 0 and n_reused == 0:
        msgs.append("*** WARNING: 0 rows generated AND 0 reused — ALL fell back to the "
                    "original response. This output is a no-op (not the Gemini responder). "
                    "Check API key / model / generation_config before submitting. ***")
    if n_fb:
        preview = ", ".join(str(s) for s in fallback_sids[:10])
        msgs.append(f"*** {n_fb}/{total} rows FELL BACK to their original response "
                    f"(no fresh/reused responder output) — sessions: {preview}"
                    f"{' ...' if n_fb > 10 else ''}. If the input came from "
                    f"--retrieval_only these are 'ok' stubs that score ~1/5 — DO NOT submit. ***")
    ok = not (fail_on_fallback and n_fb)
    return {"ok": ok, "exit_code": 0 if ok else 1, "messages": msgs}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pred", required=True, help="existing prediction.json (keeps predicted_track_ids)")
    ap.add_argument("--out", required=True, help="output prediction.json with regenerated responses")
    ap.add_argument("--dataset", default=DEFAULT_DATASET, help="HF dataset for conversation context (split=test)")
    ap.add_argument("--top-n", type=int, default=1, help="how many reranked tracks the responder sees")
    ap.add_argument("--limit", type=int, default=0, help="cap rows (0 = all)")
    ap.add_argument("--sleep", type=float, default=0.2, help="seconds between API calls")
    ap.add_argument("--cache-dir", default=None,
                    help="disk cache for responses (rerun-free); keyed by prompt+model+best_of. "
                         "Point it at a persistent path (e.g. Drive) to skip re-paying on reruns.")
    ap.add_argument("--reuse-from", default=None,
                    help="a PRIOR prediction.json (or a saved submission .zip, e.g. on Drive); "
                         "reuse its predicted_response for any row whose top_n track_ids are "
                         "unchanged -> only genuinely changed rows hit Gemini. Use a file from the "
                         "SAME responder config (model/top_n/best_of).")
    ap.add_argument("--structured-personality", action="store_true",
                    help="structured_personality (CoT) mode: the model fills personalization axes "
                         "(mood/intent/energy/sonic_pref/era_pref/familiarity) + a per-axis track "
                         "'fit' before writing; only the JSON `reply` is submitted")
    ap.add_argument("--best-of", type=int, default=1,
                    help="best-of-N: generate N replies (varied temperature), score each with the "
                         "judge model, submit the highest-scoring (1 = single shot, default)")
    ap.add_argument("--judge-model", default=JUDGE_MODEL,
                    help="model that scores best-of-N candidates (default: cheap flash)")
    ap.add_argument("--thinking-budget", type=int, default=THINKING_BUDGET,
                    help="gemini-2.5 thinking token budget. 0 = DISABLED (default) — fixes the "
                         "empty-Part/finish_reason=STOP failure (.text raises) and is much faster. "
                         "pro can't run at 0 and is clamped to its 128 minimum.")
    ap.add_argument("--max-output-tokens", type=int, default=MAX_OUTPUT_TOKENS,
                    help="hard cap on response tokens (runaway guard; unused tokens are free).")
    ap.add_argument("--fail-on-fallback", action="store_true",
                    help="exit nonzero if ANY row falls back to its original response "
                         "(no fresh Gemini output, no warm-start reuse). USE FOR SUBMISSIONS: "
                         "with a --retrieval_only input the original is the 'ok' stub, which "
                         "would silently ship and score ~1/5 on the LLM axis (config-209 bug).")
    args = ap.parse_args()

    if args.top_n < 1:
        sys.exit("ERROR: --top-n must be >= 1 (the responder needs at least one track to explain).")
    if args.best_of < 1:
        sys.exit("ERROR: --best-of must be >= 1.")
    key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not key:
        sys.exit("ERROR: set GEMINI_API_KEY (Colab secret) before running.")
    from google import genai
    from google.genai import types
    from datasets import load_dataset
    client = genai.Client(api_key=key)
    model = GenModel(client, types, MODEL, args.max_output_tokens, args.thinking_budget)
    judge_model = (GenModel(client, types, args.judge_model, args.max_output_tokens,
                            args.thinking_budget) if args.best_of > 1 else None)

    preds = json.load(open(args.pred))
    if args.limit:
        preds = preds[: args.limit]
    mode = "structured_personality" if args.structured_personality else "plain"
    bo = f", best_of={args.best_of} (judge={args.judge_model})" if args.best_of > 1 else ""
    think = "thinking=OFF" if args.thinking_budget == 0 else f"thinking={args.thinking_budget}"
    print(f"[responder] {len(preds)} rows from {args.pred} via {MODEL} "
          f"(top_n={args.top_n}, mode={mode}, {think}, max_out={args.max_output_tokens}{bo})")

    ds = load_dataset(args.dataset, split="test")
    sess_by_id = {s["session_id"]: s for s in ds}
    item_db_meta = _load_item_meta()

    reuse_map = load_reuse_map(args.reuse_from)
    if reuse_map:
        print(f"[responder] reuse-from: {len(reuse_map)} prior rows loaded from {args.reuse_from}")

    out_rows, n_gen, n_fallback, n_reused = [], 0, 0, 0
    fallback_sids: list = []
    for i, p in enumerate(preds):
        # Per-row guard: a single malformed session (unexpected schema, missing
        # conversations, bad goal shape) falls back to the original response
        # instead of aborting the whole run. Row count is always conserved.
        fallback = p.get("predicted_response", "") or ""
        prior = None
        try:
            sess = sess_by_id.get(p["session_id"])
            # Warm-start: reuse a prior response when the shown (top_n) tracks are
            # unchanged -> no Gemini call for that row.
            prior = reuse_response(reuse_map, p["session_id"], p.get("turn_number"),
                                   p.get("predicted_track_ids"), args.top_n)
            if prior is not None:
                new_resp = prior
            elif sess is None:
                new_resp = fallback
            else:
                ctx = render_context(sess["conversations"], item_db_meta, p["turn_number"])
                tracks = format_tracks(p.get("predicted_track_ids"), item_db_meta, n=args.top_n)
                goal = ((sess.get("conversation_goal") or {}).get("listener_goal") or "").strip()
                if args.structured_personality:
                    prompt = build_structured_prompt(ctx, tracks, goal)
                    parse_fn = parse_structured_reply
                else:
                    prompt = build_prompt(ctx, tracks, goal)
                    parse_fn = None
                if args.best_of > 1:
                    def _gen():
                        return generate_best_of_n(model, judge_model, prompt, ctx, tracks,
                                                  fallback, n=args.best_of,
                                                  temperatures=list(DEFAULT_TEMPS),
                                                  parse_fn=parse_fn)
                else:
                    def _gen():
                        return generate_response(model, prompt, fallback, parse_fn=parse_fn)
                new_resp = cached_response(args.cache_dir, prompt, MODEL, args.best_of,
                                           _gen, fallback,
                                           cache_salt=f"tb{args.thinking_budget}")
        except Exception as e:  # noqa: BLE001 — never let one row kill the run
            print(f"  row {i} ({p.get('session_id')}): error, keeping original response: {e!r}")
            new_resp = fallback
            prior = None
        if prior is not None:
            n_reused += 1            # warm-started from --reuse-from, no Gemini call
        elif new_resp == fallback:
            n_fallback += 1
            fallback_sids.append(p.get("session_id"))
        else:
            n_gen += 1
        out_rows.append(build_output_row(p, new_resp))
        if args.sleep and prior is None and new_resp != fallback:
            time.sleep(args.sleep)   # only pace actual API calls (skip reused/fallback rows)
        if (i + 1) % 25 == 0:
            print(f"  {i+1}/{len(preds)} (generated={n_gen}, reused={n_reused}, fallback={n_fallback})")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    json.dump(out_rows, open(args.out, "w"), ensure_ascii=False)
    print(f"\n[responder] wrote {len(out_rows)} rows -> {args.out} "
          f"(generated={n_gen}, reused={n_reused}, fallback={n_fallback})")
    # Loud guard: surface fallback rows (kept their ORIGINAL response — a no-op for
    # that row; a leaked 'ok' stub under --retrieval_only) and the all-fallback
    # no-op. With --fail-on-fallback, abort so a stub/stale response can't ship.
    report = summarize_run(n_gen, n_reused, fallback_sids, len(out_rows), args.fail_on_fallback)
    for m in report["messages"]:
        print("\n" + m)
    if not report["ok"]:
        # NOTE: this nonzero exit only halts a caller that checks the return code
        # (subprocess.run(check=True)). A notebook `!`-magic line does NOT propagate
        # it — there, precheck_prediction.py (run after, check=True) is the real gate
        # (the output file is already written above, so precheck still sees the stubs).
        sys.exit(report["exit_code"])


if __name__ == "__main__":
    main()
