from typing import List, Optional

import torch

# CRS_BASELINE is lazily imported inside load_crs_baseline() so that submodule
# access like `from mcrs.sid.preprocessing import ...` does NOT eagerly trigger
# the full retriever cascade (BM25, dense, CMQR, etc., each with their own
# heavy deps). Callers of load_crs_baseline pay the cascade cost on first call,
# same as before.

def load_crs_baseline(
    lm_type="meta-llama/Llama-3.2-1B-Instruct",
    retrieval_type="bm25",
    item_db_name: str = "talkpl-ai/TalkPlayData-Challenge-Track-Metadata",
    user_db_name: str = "talkpl-ai/TalkPlayData-Challenge-User-Metadata",
    track_split_types: list[str] = ["all_tracks"],
    user_split_types: list[str] = ["all_users"],
    corpus_types: list[str] = ["track_name", "artist_name", "album_name"],
    cache_dir="./cache",
    device="cuda",
    attn_implementation="eager",
    dtype=torch.bfloat16,
    response_prompt_name: str = "response_generation",
    reranker_type: Optional[str] = None,
    reranker_model_path: Optional[str] = None,
    retrieval_topk: int = 20,
    response_max_new_tokens: int = 64,
    top_n_for_prompt: int = 1,
    query_preprocessing_mode: str = "raw",
    response_reranker_type: Optional[str] = None,
    response_reranker_model_path: Optional[str] = None,
    response_n_candidates: int = 3,
    response_temperatures: Optional[List[float]] = None,
    use_vllm: bool = False,
    lora_path: Optional[str] = None,
    lora_max_rank: int = 32,
    use_state_tracker: bool = False,
    state_tracker_prompt_name: str = "state_extraction",
    state_tracker_max_new_tokens: int = 96,
    use_cmqr: bool = False,
    cmqr_prompt_name: str = "cmqr_rewrites",
    cmqr_n_rewrites: int = 4,
    cmqr_topk_per_rewrite: int = 50,
    cmqr_rrf_k: int = 60,
    cmqr_max_new_tokens: int = 96,
):
    from .crs_baseline import CRS_BASELINE  # lazy: see module-level comment
    return CRS_BASELINE(
        lm_type=lm_type,
        retrieval_type=retrieval_type,
        item_db_name=item_db_name,
        user_db_name=user_db_name,
        track_split_types=track_split_types,
        user_split_types=user_split_types,
        corpus_types=corpus_types,
        cache_dir=cache_dir,
        device=device,
        attn_implementation=attn_implementation,
        dtype=dtype,
        response_prompt_name=response_prompt_name,
        reranker_type=reranker_type,
        reranker_model_path=reranker_model_path,
        retrieval_topk=retrieval_topk,
        response_max_new_tokens=response_max_new_tokens,
        top_n_for_prompt=top_n_for_prompt,
        query_preprocessing_mode=query_preprocessing_mode,
        response_reranker_type=response_reranker_type,
        response_reranker_model_path=response_reranker_model_path,
        response_n_candidates=response_n_candidates,
        response_temperatures=response_temperatures,
        use_vllm=use_vllm,
        lora_path=lora_path,
        lora_max_rank=lora_max_rank,
        use_state_tracker=use_state_tracker,
        state_tracker_prompt_name=state_tracker_prompt_name,
        state_tracker_max_new_tokens=state_tracker_max_new_tokens,
        use_cmqr=use_cmqr,
        cmqr_prompt_name=cmqr_prompt_name,
        cmqr_n_rewrites=cmqr_n_rewrites,
        cmqr_topk_per_rewrite=cmqr_topk_per_rewrite,
        cmqr_rrf_k=cmqr_rrf_k,
        cmqr_max_new_tokens=cmqr_max_new_tokens,
    )
